### ISSUE TITLE
Add curl

### ISSUE THREAD

**Issue by elmerfdz** [crazy-max/docker-fail2ban#1]
Hi there, good work on this f2b image, it's way better than the ones I've tried. 

If you don't mind, I've got a request, could you please add curl to this as well? I use cloudflare and the cloudflare action requires curl.

Thanks

**Comment by crazy-max** [comment]
Hi @elmerfdz, curl has been added, thanks for your input :)

**Comment by elmerfdz** [comment]
Thanks once again, got everything setup and the container is working better than a native f2b install :)

**Comment by crazy-max** [comment]
Glad to here that :tada:
