### ISSUE TITLE
sshd: can't find failed attempts

### ISSUE THREAD

**Issue by jribal** [crazy-max/docker-fail2ban#10]
Hi, I successfully setup fail2ban to block traefik error 401 but it seems like the regex can't pick my sshd error attempts.

I have this log when I enable debug and an attempt is made:
`[1]: DEBUG   /var/log/auth.log has been modified`

On auth.log I have this log:
```sshd[27292]: Invalid user xxxx from x.x.x.x port 54768
sshd[27292]: input_userauth_request: invalid user xxxx [preauth]
sshd[27292]: pam_unix(sshd:auth): check pass; user unknown
sshd[27292]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=x.x.x.x
sshd[27292]: Failed password for invalid user xxxx from x.x.x.x port 54768 ssh2
sshd[27292]: Received disconnect from x.x.x.x port 54768:11: Bye Bye [preauth]
sshd[27292]: Disconnected from x.x.x.x port 54768 [preauth]
```
I used your example, do you know why it would fail this way ?
Thanks for this docker image by the way, there is more documentation and all options seems easier to use than other images.

**Comment by crazy-max** [comment]
Hi @jribal, what is the distrib and version of your host please ?
The [current example for sshd](https://github.com/crazy-max/docker-fail2ban/blob/master/examples/jails/sshd/jail.d/sshd.conf) works for me on Debian 9 and uses the [default sshd filter](https://github.com/fail2ban/fail2ban/blob/0.11/config/filter.d/sshd.conf) provided by Fail2ban. Take a look at the configuration of this filter. Maybe you have to choose a different mode.

**Comment by jribal** [comment]
Hi @crazy-max, thank you for your answer.

I'm using debian 9.6, almost everything is on default configuration.

Thank you for the configuration link, I will attempt to add a working filter for me.

**Comment by crazy-max** [comment]
@jribal Oh nice catch, I assume you have changed the `TZ` env var for the container ?

**Comment by jribal** [comment]
Exactly, I used `TZ` . I got lucky to find this error, it's hard to spot.
