### ISSUE TITLE
Default chain does not block ssh traffic

### ISSUE THREAD

**Issue by jribal** [crazy-max/docker-fail2ban#11]
Hi, I'm using debian 9.6 and Docker version 18.06.1-ce. sshd is on default port 22 and I'm using example sshd.conf.
I found many "already banned" messages on logs. I try to banned my self and realised I could still connect to ssh while being banned.

Iptable line inserted by fail2ban:
`REJECT     all  --  xx.xx.xx.xx  anywhere             reject-with icmp-port-unreachable`

It appears `DOCKER-USER` chain does not block ssh traffic at all for me. 
I had to set environment to : ` - F2B_IPTABLES_CHAIN=INPUT`

I'm using a [traefik rule](https://gist.github.com/acundari/9bdcf2ba0c0f8a4bf59a21d06da35612) that works fine.
Here's my thought: `DOCKER-USER` chain works fine for a container block but blocking sshd on host does not work. If it is the case it would be nice to add a warning on documentation.

**Comment by crazy-max** [comment]
You right, if fail2ban is attached to `DOCKER-USER` chain instead of `INPUT`, the rules will be applied only to containers. This means that any packets coming into the INPUT chain will bypass these rules that now reside under the FORWARD chain. So sshd jail will not work as intended. You can create another container to attach fail2ban to `INPUT` chain for example. I will add a note about this, thanks for your input!

**Comment by crazy-max** [comment]
@jribal Check [this section](https://github.com/crazy-max/docker-fail2ban#docker-user-and-input-chains). This is an easy workaround solution, but I think we can improve the configuration of the iptables-multiport action and use only one container.

**Comment by jribal** [comment]
I'm no fail2ban or iptables expect, from what I read multiport allows to block more than the port attacked. I tried to block all ports on failure and I still had my "already banned", maybe you can do better.

My use case is using your container as a regular fail2ban installed on host. Except for tests or really specific setup, I don't see why would somebody wants to reject only traffic coming to "docker network" excluding host.

For me `INPUT` should be default but it depends on which behavior you expect.
