### ISSUE TITLE
Sendmail Report

### ISSUE THREAD

**Issue by Ajeris** [crazy-max/docker-fail2ban#115]
Hello, enjoying your wonderful build. but I can't solve the problem of sending emails to me about blocked ip addresses. by trial and mistakenly realized that the environment entries:
      - SSMTP_HOST=mail.domain.com
      - SSMTP_PORT=25
      - SSMTP_HOSTNAME:nmp.local
      - SSMTP_USER=pandora@domain.com
      - SSMTP_PASSWORD=pass_mailbox
      - SSMTP_TLS=NO
      - SSMTP_STARTTLS=YES
 should be something like the correctness of the settings checked with the command echo "Subject: sendmail test" | sendmail -v admin@domain.com from the container then added entries to the npm-docker.local file:
destemail=admin@domain.com
sender = root@$(hostname -f)
caused the blocking of the address but the messages do not reach, tell me what I'm doing wrong.

**Comment by crazy-max** [comment]
Any useful logs in the container?

**Comment by Ajeris** [comment]
Thanks!! dealt with this problem.

**Comment by shooftie** [comment]
![image](https://github.com/crazy-max/docker-fail2ban/assets/2161844/0bbfc40a-7066-4970-a80d-24b97065a302)
