### ISSUE TITLE
Sendmail "wrong parameters" issue , always the first time execution of "sendmail" command,second try always okay.

### ISSUE THREAD

**Issue by Tino4** [crazy-max/docker-fail2ban#117]
#Always an error "wrong parameters" after the command sendmail , second try of this command is always okay ,Then when i wait a while ,the same problem.
???
Best Regards , elektrofreak

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/crazy-max/docker-fail2ban/issues/new?assignees=&labels=&template=bug_report.md).
