### ISSUE TITLE
Consider adding mail standalone feature

### ISSUE THREAD

**Issue by Gandulf78** [crazy-max/docker-fail2ban#118]
Actually it is a feature request.
I've set up Fail2ban on my NAS (WDMyCloudEX2Ultra) to protect VaultWarden and it is working fine. I would like to set-up the mail feedback but unfortunately there's no email app (sendmail or mail) working on the NAS so it is not working. The python mail option is not working either. 
I am using other Docker images which are including email functionality (with heirloom-mailx) and are working perfectly fine. Could you please consider including this one in your Docker image ? (Unfortunately I can't build it myself due to libseccomp outdated on the NAS OS based on armv7). 
Thank you.

**Comment by crazy-max** [comment]
> The python mail option is not working either.

I would say [`SSMTP_*` env vars](https://github.com/crazy-max/docker-fail2ban#environment-variables) are not configured properly for your mail provider. Hard to tell without logs. Please create a proper [bug report](https://github.com/crazy-max/docker-fail2ban/issues/new?assignees=&labels=&template=bug_report.md).
