### ISSUE TITLE
F2B_DB_PURGE_AGE in examples is bogus

### ISSUE THREAD

**Issue by tomers** [crazy-max/docker-fail2ban#128]
### Behaviour

In https://github.com/crazy-max/docker-fail2ban/blob/master/examples/compose/fail2ban.env, there's:
```
F2B_DB_PURGE_AGE=1d
```
However this environment variable exist neither in this repo or in fail2ban's repo.

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-fail2ban/blob/9f379d0903875859fa514a1008efbd07b54e7057/entrypoint.sh#L77

**Comment by tomers** [comment]
Got it. Thanks for the prompt reply, and sorry to have wasted your time!
