### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by PhasecoreX** [crazy-max/docker-fail2ban#13]
When Fail2Ban tries to ban a user with an IPv6 address, I get the following error:

stderr: '/bin/sh: ip6tables: not found'

It doesn't seem like you have the ip6tables program installed in this container. Can this be added?

**Comment by crazy-max** [comment]
Hi @PhasecoreX,

I will take a look asap but it seems feasable, thanks

**Comment by crazy-max** [comment]
Done
