### ISSUE TITLE
Warning message is always triggered: already exists and will be overriden

### ISSUE THREAD

**Issue by kosli** [crazy-max/docker-fail2ban#133]
I am using docker-compose with the container and the mentioned warning message is always triggered as the symbolic link already exists: https://github.com/crazy-max/docker-fail2ban/blob/170a02310bda33c445997aa087573b5c6a9d79ec/entrypoint.sh#L83
So the check should be if the file exists and is NOT already the right target?

**Comment by crazy-max** [comment]
This warning is legit if you're overriding a core action. You can change the action filename in your data folder if this is not done on purpose.
