### ISSUE TITLE
add linux/arm/v8 image

### ISSUE THREAD

**Issue by asmod3us** [crazy-max/docker-fail2ban#170]
### Description

Hello, would it be possible to build an image for `linux/arm/v8` as well?

**Comment by crazy-max** [comment]
There is no such arch as arm with v8 variant. Arm v8 is actually arm64 which is available with this image as `linux/arm64` platform.

**Comment by asmod3us** [comment]
Thanks, for some reason docker required `--platform linux/arm64` to run on Apple SIlicon. It was looking for variant `linux/arm64/v8` without it.

**Comment by crazy-max** [comment]
> Thanks, for some reason docker required `--platform linux/arm64` to run on Apple SIlicon. It was looking for variant `linux/arm64/v8` without it.

The platform `linux/arm64/v8` will be normalized as `linux/arm64`.
