### ISSUE TITLE
fail2Ban banning Nextcloud Users

### ISSUE THREAD

**Issue by Soarnoa** [crazy-max/docker-fail2ban#19]
I set up a fail2ban container, and now when I access any security settings in nextcloud, I get banned. and I can't seem to figure out why. If I'd guess, the regex for traefik-auth is misparsing something,

Here's my fail2ban log: https://hastebin.com/secunuhepi.pl
My traefik access logs: https://hastebin.com/edidorijav.pl

EDIT: Seems to be banning nextcloud webdav users as well.
Forgot to mention that I'm using the example scripts provided for traefik.

**Comment by crazy-max** [comment]
traefik-auth filter has been added on the official repository : https://github.com/fail2ban/fail2ban/blob/0.11/config/filter.d/traefik-auth.conf
I will add a note about this.
