### ISSUE TITLE
Works on host connections

### ISSUE THREAD

**Issue by ytzelf** [crazy-max/docker-fail2ban#2]
Just to make sure, this blocks connections to host as well correct?

**Comment by crazy-max** [comment]
Yep, [network_mode must be set to host and privileged enabled](https://github.com/crazy-max/docker-fail2ban/blob/master/examples/compose/docker-compose.yml#L7-L8).

To check if an IP is banned on your host, type `iptables -S | grep f2b`.

Example with sshd jail :

```
-N f2b-sshd
-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
-A f2b-sshd -s 10.0.0.1/32 -j REJECT --reject-with icmp-port-unreachable
-A f2b-sshd -j RETURN
```

**Comment by Folas1337** [comment]
So the host needs iptables if you want this to work?
I didn't know that and you might want to include it in the README so people check for that.

I've been wondering why it wasn't working, I'll install iptables now and report back
