### ISSUE TITLE
Add white IP's and different ban times

### ISSUE THREAD

**Issue by Rathorian** [crazy-max/docker-fail2ban#20]
Hello,

I would have liked to know how to add and persist white IPs and different ban times than is already preconfigured.

Thank you.

**Comment by crazy-max** [comment]
For all matters directly related to fail2ban, please search first on the official repository : fail2ban/fail2ban#123

**Comment by mikeg-de** [comment]
@crazy-max you closed the ticket you referenced and this one at the same day. Though, the referenced one is still a ledig request. Isn't it?
