### ISSUE TITLE
ignoreips

### ISSUE THREAD

**Issue by danteali** [crazy-max/docker-fail2ban#21]
Thanks for the great image. 

While I can manually map my own jail.local and include the `ignoreip` config setting I'd rather not do that since you've got everything else working through env vars. 

Can we add another env var for `ignoreip`?

**Comment by danteali** [comment]
I'm going to mark this one as closed.

Turns out you can add `ignoreip = 1.2.3.4 5.6.7.8` to each jail individually, doesn't need to be set at the jail.conf/jail.local level.

**Comment by crazy-max** [comment]
@danteali We can do this globally in `jail.local` file at startup. But looking at fail2ban/fail2ban#392 I think we should use `jail.d/*.local` to do that instead of using  environment variables. This will make it more maintainable and intuitive for the user. I'll think about that.
