### ISSUE TITLE
sendmail hangs

### ISSUE THREAD

**Issue by simontong** [crazy-max/docker-fail2ban#26]
I followed the instructions to set up two containers (one for INPUT one for DOCKER-USER).

`.env` file is as follows:

```
TZ=UTC
F2B_LOG_TARGET=STDOUT
F2B_LOG_LEVEL=DEBUG
F2B_DB_PURGE_AGE=1d
F2B_MAX_RETRY=3
F2B_DEST_EMAIL=xxx@xxx.com
F2B_SENDER=xxx2@xxx.com
F2B_ACTION=%(action_mw)s
F2B_IPTABLES_CHAIN=DOCKER-USER
SSMTP_HOST=smtp
SSMTP_PORT=587
SSMTP_HOSTNAME=xxx.com
SSMTP_USER=xxx2@xxx.com
SSMTP_PASSWORD=xxxxxx
SSMTP_TLS=YES
```

When someone gets banned it should be sending me an email but it does not appear to do anything.

I tried entering the container and executing `sendmail` and it simply hangs and I have to do a `kill <pid>` on it to end.

Any ideas how to fix this ?

Thanks

**Comment by crazy-max** [comment]
@simontong Cannot reproduce your issue. Maybe a connection timeout. Have you tried with an other smtp server ?
