### ISSUE TITLE
Log attachment automation

### ISSUE THREAD

**Issue by rexdjw** [crazy-max/docker-fail2ban#27]
Hi Max,
Thanks for all your hard work on this project!

I was wondering about the log system implementation with compose though. Since the startup requires logs -f, I'm wondering how I might bake this into restart policies? If the system goes down, or the docker gets detattached from the console log output for some reason..would you have any recommendations for tieing them together? 

Thanks

**Comment by crazy-max** [comment]
Hi @rexdjw,

Sorry for the delay, pretty busy those days :rocket:

By default, Docker captures the standard output (and standard error) of containers, and writes them in files using the JSON format using the default [JSON File logging driver](https://docs.docker.com/config/containers/logging/json-file/).

About compose, If you don't change the name of root folder of your compose file and service name inside log will be kept across restart or host shutdown. You can [docker inspect](https://docs.docker.com/engine/reference/commandline/inspect/) your container to see where their logs are:

```
$ docker inspect --format='{{.LogPath}}' <container id/name>
```

If you want to manage logs yourself, you can use `F2B_LOG_TARGET` to change log target. You can use `/data/failban.log` to keep log persisted for example.
