### ISSUE TITLE
ARMv7 Image

### ISSUE THREAD

**Issue by TheMardy** [crazy-max/docker-fail2ban#30]
Hi Max,
Thanks for your hard work on this project!

Can you add an ARMv7 image to make it run on a Raspberry Pi?
I can confirm it works fine if the Dockerfile is built on a pi, so the only change would be to use the Alpine ARMv7 as base image.

Thanks.

**Comment by crazy-max** [comment]
Hey @TheMardy,

Yes I'm preparing the ground to make most of [my Docker images](https://hub.docker.com/r/crazymax/) multi-platform ;)
For the moment [docker-cloudflared](https://github.com/crazy-max/docker-cloudflared) and [docker-firefox-syncserver](https://github.com/crazy-max/docker-firefox-syncserver) are available as multi-platform and fail2ban is on my todolist ;)

**Comment by crazy-max** [comment]
@TheMardy Done

```
λ docker run --rm mplatform/mquery crazymax/fail2ban:latest
Image: crazymax/fail2ban:latest
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x
```
