### ISSUE TITLE
jail.local overwritten on start

### ISSUE THREAD

**Issue by iCounsellorUK** [crazy-max/docker-fail2ban#31]
Firstly - thanks very much for this image. It's working wonderfully!

### Behaviour

CURRENT BEHAVIOUR: upon execution, entrypoint.sh writes default values into /etc/fail2ban/jail.local - effectively creating jail.local from scratch. It does this every time the container is run .. as designed.

However, I'd recommend that FAIL2BAN's philosophy for jail.local is that it be used to define custom behaviour (i.e. if I wanted to add a new action & jail I would do so by amending jail.local).

Following best-practices (I hope!) for Docker Swarm, I map a volume to jail.local and amend my jail.local file:-

fail2ban.yaml (my file!)
     volumes:
         - /media/nas/common/fail2ban/jail.local:/etc/fail2ban/jail.local

... but of course when entrypoint.sh runs it erases my amendments to jail.local ( entrypoint.sh: cat > ) by creating jail.local from scratch.

If you agree with my position, I would recommend making a slight amendment to entrypoint.sh as follows:-

# Patch - only initialise the jail.local if it doesn't exist
if [ ! -f /etc/fail2ban/jail.local ] ; then
cat > /etc/fail2ban/jail.local <<EOL
[DEFAULT]
maxretry = ${F2B_MAX_RETRY}
backend = ${F2B_BACKEND}
destemail = ${F2B_DEST_EMAIL}
sender = ${F2B_SENDER}
action = ${F2B_ACTION}
EOL
fi

#### Steps to reproduce this issue

1. Mount /etc/fail2ban/jail.local to a file on the host system
2. Amend the host system's jail.local
3. Bring up docker-fail2ban container
4. both the host and the container's /etc/fail2ban/jail.local loses all amendments.

#### Expected behaviour

> Tell me what should happen

The current entrypoint.sh does exactly what it's designed to do - creating /etc/fail2ban/jail.local from scratch each time the container is run.

My suggestion is amend entrypoint.sh so that it only creates jail.local if the file doesn't already exist. In that way developers can amend the execution of fail2ban using amendments to jail.local

**Comment by crazy-max** [comment]
Hi @iCounsellorUK,

You can already override fields of the generated `jail.local` of this image.
As explained on the [jail.conf(5) man page](https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html#CONFIGURATION_FILES_FORMAT), configuration files are loaded in this order:

```
jail.conf
jail.d/*.conf (in alphabetical order)
jail.local
jail.d/*.local (in alphabetical order)
```

In our case you have to place your custom jail local in `/data/jail.d/00-jail.local` for example.
Can you try this?

And thanks for your support!
