### ISSUE TITLE
Is it possible to integrate fail2ban in an simple ssh docker container?

### ISSUE THREAD

**Issue by rubkec** [crazy-max/docker-fail2ban#32]
Hi, 

is it possible to integrate fail2ban in a alpine docker with an simple OpenSSH Server running?
or does fail2ban only works on the docker host?

**Comment by crazy-max** [comment]
Hi,

I don't really see the purpose of integrating SSH into a Docker image but theoretically you can do it by making a mount bind of the SSH access logs of your Alpine image to the Fail2ban image and create a similar sshd jail as [this one](https://github.com/crazy-max/docker-fail2ban/blob/master/examples/jails/sshd/jail.d/sshd.conf).
