### ISSUE TITLE
Make it possible to run the container as non root

### ISSUE THREAD

**Issue by Akruidenberg** [crazy-max/docker-fail2ban#34]
It would be nice to run this container with another user.  
With your firefox-sync image, you can run it with a PUID/PGID var.
Is it possible to do this with fail2ban also?

edit: tested with PUID/PGID vars with docker compose. The container is stil running as root. the user command don't work.

**Comment by Akruidenberg** [comment]
Any progress?

**Comment by crazy-max** [comment]
@Akruidenberg 

> Make it possible to run the container as non root

Even with [linux capabilities](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) we use today (NET_RAW / NET_ADMIN) with this image, we have to deal with the host kernel to be able to use the `xt_recent` kernel module for iptables and also to read the log files. So no direct possibility to use a non-root user with this image.

**Comment by damianperera** [comment]
I run this image without root on CentOS 8 (took a bit of fine-tuning to get it to work with `xtables-nft-multi`)

**Comment by damianperera** [comment]
I run this image as a non-root user on CentOS 8 (took a bit of fine-tuning to get it to work with `xtables-nft-multi`)
