### ISSUE TITLE
traefik 2.1 not working (can't set timezone in traefik accesslogs [always UTC])

### ISSUE THREAD

**Issue by bd8392** [crazy-max/docker-fail2ban#35]
There are multiple closed issues about traefik, and I read most of them...I still can't figure out, what I'm doing wrong...I use traefik with basic auth on docker containers...I followed exactly your steps...ssh is working, traefik not...it siply shows no action in the logs...except that it is adding the traefik access log...please help!

**Comment by bd8392** [comment]
Tried this one: but is not working...I tried it with json and non-json log...no difference...
https://github.com/crazy-max/docker-fail2ban/issues/35

**Comment by bd8392** [comment]
output of accesslog:

'''
192.168.100.110 - - [16/Jan/2020:20:31:43 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 1 "backend@docker" - 0ms
192.168.100.110 - - [16/Jan/2020:20:31:44 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 2 "backend@docker" - 0ms
192.168.100.110 - - [16/Jan/2020:20:32:06 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 3 "backend@docker" - 0ms
192.168.100.110 - - [16/Jan/2020:20:38:46 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 1 "backend@docker" - 0ms
192.168.100.110 - - [16/Jan/2020:20:38:47 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 2 "backend@docker" - 2ms
192.168.100.110 - - [16/Jan/2020:20:38:59 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 3 "backend@docker" - 0ms
192.168.100.110 - - [16/Jan/2020:20:39:02 +0000] "GET / HTTP/2.0" 401 17 "-" "-" 4 "backend@docker" - 0ms
'''

**Comment by crazy-max** [comment]
Hi @bd8392,

Can you try this failregex:

`failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .+\" 401 .+$`

**Comment by bd8392** [comment]
works perfectly! thanks! =) I spend hours with it! Was really great help =)

**Comment by bd8392** [comment]
ok this works a little to good...it bans me after the first wrong password, but i set 3 attempts in the variables...it also shows that it found three attempts...

**Comment by crazy-max** [comment]
@bd8392 Can you post log samples please?

**Comment by crazy-max** [comment]
@bd8392 This issue is linked to Traefik and not directly to Fail2ban or this image. You can get support on https://github.com/containous/traefik

**Comment by bd8392** [comment]
Ok thank you :-)
