### ISSUE TITLE
Best way to unban

### ISSUE THREAD

**Issue by mattthhdp** [crazy-max/docker-fail2ban#37]
i have banned myself (for testing purposes) at the office. Everything is working as it should... but know what is the best way to unban ip

**Comment by devops-caspian** [comment]
Unban one ip:
docker exec -t <CONTAINER> fail2ban-client set <JAIL> unbanip <IP>
Unban all:
docker exec -t <CONTAINER> fail2ban-client unban --all

**Comment by mattthhdp** [comment]
Thank you very much!
