### ISSUE TITLE
SMTP example?

### ISSUE THREAD

**Issue by ptruman** [crazy-max/docker-fail2ban#52]
Is there a good example config for the SMTP setup?
I've setup the ENV but can't get it to fire on a ban....

sendmail myuser@mydomain.com works fine though, so the wiring is correct, but my jail/f2b config is clearly "not right"

Pointers appreciated :)

**Comment by crazy-max** [comment]
Hi @ptruman,

I need more info (like logs). Please create a proper [bug report](https://github.com/crazy-max/docker-fail2ban/issues/new?template=bug_report.md). Thanks.

**Comment by ptruman** [comment]
I was just after a config example like you had for traefik etc - i.e. ENV setup (I can see those examples) and an example in jail.d or actions.d and jail.local :)

I've had plenty of fun today getting this working with traefik 2,2.5 (only INPUT seems to work properly for me) and got stymied by fail2web not behaving, so it was just a request for sample configs - I can probably spot what I'm missing from those, rather than enabling DEBUG, restarting and poking it a bit :)

**Comment by crazy-max** [comment]
@ptruman There is an example in [this section](https://github.com/crazy-max/docker-fail2ban#global-jail-configuration). Then you can use the `SSMTP_*` env vars defined [here](https://github.com/crazy-max/docker-fail2ban#environment-variables).

**Comment by ptruman** [comment]
Thanks.
If I put a jail.conf/jail.local file in the folder above jail.d/filter.d -
it's not read
But if I put the contents of the file in the individual .local jail file
it's working :)
