### ISSUE TITLE
Included whois can't lookup ip

### ISSUE THREAD

**Issue by ytzelf** [crazy-max/docker-fail2ban#6]
Embedded whois can't lookup by IP; outputs

> [Querying whois.iana.org:43 '5.188.10.76']
[Querying whois.iana.org:43 'domain 5.188.10.76']
[whois.iana.org]
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
%
% Error: Invalid query domain 5.188.10.76

Was able to circumvent the bug by manually apk adding whois in a dockerfile but you might as well do it here; happy to fill a PR if needed

**Comment by crazy-max** [comment]
Hi @ytzelf, yeah feel free to open a PR thx.

**Comment by crazy-max** [comment]
Included in the latest image, thanks for your contrib :)
