### ISSUE TITLE
Dockerhub images - latest and edge

### ISSUE THREAD

**Issue by Roberto6969** [crazy-max/docker-fail2ban#70]
Hello, thank you for your great work. This is not an issue - I apologize using this way for question.
What is the difference between "latest" and "edge" image tag on dockerhub?
Thank You!

**Comment by crazy-max** [comment]
Hi @Roberto6969,

* [`latest`](https://hub.docker.com/r/crazymax/fail2ban/tags?page=1&ordering=last_updated) tag is the latest release/version. Today linked to `0.11.1` (stable).
* `edge` reflects the latest changes of the master branch (unstable).
