### ISSUE TITLE
Ban ip on a docker service behind a reverse-proxy

### ISSUE THREAD

**Issue by schklom** [crazy-max/docker-fail2ban#83]
Hi,

Would someone please help me define ports to ban ?

I am running a service (exposing port 1234:80) behind a reverse-proxy (exposing port 5678:443).
I am able to ban ips when using `port = https`. The problem is that this also bans access to any other service because it (I think) is banning access on port 5678 instead of only 1234.

I have tried using

    port = 1234

but it doesn't prevent anything.

Does anyone know if there a way to only ban access to a specific service behind a reverse-proxy ?

Many thanks to whoever tries to help :)

**Comment by machond** [comment]
In jail you specify more ports to watch and separate them by comma.

`port = 80,443,1234`

If I understand correctly your problem goes with action. Because your ban currently denied whole access to all ports on that machine.
`banaction = %(banaction_allports)s`

Change this to ban only specific ports in provided in jail.

**Comment by schklom** [comment]
@machond
You're right, I had set
```
banaction = %(banaction_allports)s
```
after failing with `iptables-multiport`, it was the only setting that worked.
I have tested the jail:
```
[service]
backend		= auto
enabled		= true
chain		= DOCKER-USER
port		= http,https,80,443,1234,5678,9012
protocol	= tcp
filter		= service
logpath		= %(service_log)s

banaction	= iptables-multiport
action		= %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
		  %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", sendername="%(sendername)s", fq-hostname="%(fq-hostname)s", dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
```

To prevent confusion on ports: (wan) 9012 is forwarded (lan) 5678 which is reverse-proxied to (service) 1234.
With the jail above, banned IPs can still access the service despite logs showing the bans.

My solution right now is `iptables_allports`, but is overkill.

**Comment by machond** [comment]
@schklom 
Could you try something like this? Provide direct ports in command in action and check if works:

Example:
```
action = iptables-multiport[actname=examplename-tcp, name=examplename-tcp, port="80,443,1234,5678,9012", protocol=tcp, chain="%(chain)s]
         iptables-multiport[actname=examplename-udp, name=examplename-udp, port="80,443,1234,5678,9012", protocol=udp, chain="%(chain)s]
```

**Comment by schklom** [comment]
@machond 
I am really stupid...
I was trying to ban the IP from accessing a service. But my services are always accessed through the same https port: users are redirected based on query and not port. Fail2ban cannot ban a client from submitting a query, it's all or nothing, and I just realized this now.

Sorry to have wasted your time, and thank you so much for trying to help me anyway, you're awesome ! :)
