### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by machond** [crazy-max/docker-fail2ban#85]
Could somone post working example env variables for external smtp to send info abut bans? Should I add something to jails or actions too?

Best, M.

**Comment by BeckeBauer** [comment]
I am interested too. In particular, I have no clue what is the difference between `SSMTP_HOST` and `SSMTP_HOSTNAME`?

**Comment by crazy-max** [comment]
https://github.com/crazy-max/docker-fail2ban/blob/179ad7e32324f52c387e80365525bb4cb14bb2b7/examples/compose/fail2ban.env#L7-L12

**Comment by machond** [comment]
Still cant make this work:
Could you help me a bit and take a look?

Banning work super good, but smtp notification no for me.
Env was setup good:
 SSMTP_HOST=smtp.example.com 
 SSMTP_PORT=587 
 SSMTP_HOSTNAME=mydomain.com 
 SSMTP_USER=myapiuser
 SSMTP_PASSWORD= myqpipass
 SSMTP_TLS=YES 

Current files:
`# path_f2b/jail.d/seafile.local

[seafile]
enabled = true
port = 80,443
filter = seafile-auth
banaction = %(banaction_allports)s
logpath = /seafile-main-logs/seahub.log
maxretry = 3
bantime = 14400
findtime = 14400
action = iptables-allports[name=seafile, chain=FORWARD]`

*.local
`[DEFAULT]
destemail = myemail@gmail.com
sender = myname@$(hostname -f)
action = %(action_mwl)s`

Any ideas why still emails dont show up?

**Comment by BeckeBauer** [comment]
@crazy-max: Thank you for the explanations
@machond: I managed it after I changed to port 25 without TLS (any hints in your logfile, maybe?)

**Comment by BeckeBauer** [comment]
@machond: one more thing I just noticed: try your domain instead of `$(hostname -f)` 
`sender = myname@mydomain.com `
(with `$(hostname -f)` , it did not work for me)

**Comment by machond** [comment]
@crazy-max 
Yeah, I will share my current working code. SMTP working flawless:

You need specify smtp in each jail. Sender, destmail and action. For example seafile jail:
```
# path_f2b/jail.d/seafile.local

[seafile]
destemail = destination@mail.com
sender = you@yourdomain.com
enabled = true
port = 80,443
filter = seafile-auth
banaction = %(banaction_allports)s
logpath = /seafile-main-logs/seahub.log
maxretry = 3
bantime = 14400
findtime = 14400
action = iptables-allports[name=seafile, chain=FORWARD]
			%(mta)s-whois-lines[sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s", chain="%(chain)s"]
```

Env neccessary for smtp to work. For me port 465 with tls yes working okay:
```
      - SSMTP_HOST=smtp.maildomainprovider.com
      - SSMTP_HOSTNAME=yourdomain.com
      - SSMTP_PORT=465
      - SSMTP_USER=apiusername
      - SSMTP_PASSWORD=myloginSuperSecure3123Password13231
      - SSMTP_TLS=YES
```
If not working still, go ban yourself by test and go check fail2ban.log in fail2ban folder.
If still problems, run bash in your docker container and use command and provide destination email to test:
`sendmail destination@mail.com`
Later you will need to provide some details and ctrl+d to send. 

Example:
```
[server]$ /usr/sbin/sendmail youremail@example.com
To: differentemail@example.com
From: anyone@example.com
Subject: Test Send Mail
Hello World
control d (this key combination will finish the email.)
```

**Comment by crazy-max** [comment]
@machond 

> You need specify smtp in each jail. Sender, destmail and action.

No need to specify in each jail. Can be global by specifying the `[DEFAULT]` section in a jail conf. Here is one of mine as an example:

`./data/jail.d/00-jail.local`

```text
[DEFAULT]
bantime.increment = true
bantime.overalljails = true
bantime = 1h

maxretry = 3
maxmatches = %(maxretry)s

backend = auto

destemail = webmaster@example.com
sender = fail2ban@example.com

action = %(action_mwl)s
```
