### ISSUE TITLE
Possible to use this image with user namespaces?

### ISSUE THREAD

**Issue by paulhutchings** [crazy-max/docker-fail2ban#89]
I'm running Docker with [user namespace remapping](https://docs.docker.com/engine/security/userns-remap/) (for anyone not familiar with this instead of running as root your containers run as a separate (typically unprivileged) user+group id that you generate). However, per the documentation on that page,  user namespaces are incompatible with host mode networking for containers. 

My question is, will this work as intended without host mode networking, or is that required in order to actually ban the ips and I should be looking at running fail2ban on the host directly? Networking is not my area of expertise (I've also never used anything other than the default `bridge` networking mode in Docker) so apologies if this is a seemingly absurd question.

**Comment by CaosFR** [comment]
i'm very interesting to.


If we implement this security :

$ nano /etc/daemon.json
{
        "userns-remap": "default",
}

We got this error : 
ERROR: for fail2ban  Cannot create container for service fail2ban: cannot share the host's network namespace when user namespaces are enabled

According to the Docker documentation (https://docs.docker.com/engine/security/userns-remap/) this error is bind to this param : --network=host

Does a way to solve it ?
