### ISSUE TITLE
ERROR with emby log

### ISSUE THREAD

**Issue by flux02** [crazy-max/docker-fail2ban#95]
Hi,

I have an Issue with emby logs (works without docker)

the process dont work.

 | 2021-05-21 20:56:33,892 fail2ban.filter         [1]: ERROR   Failed to process line: '2021-05-21 20:56:14.089 Warn Server: AUTH-ERROR: 192..0.0.1 - Invalid username or password entered.', caught exception: IndexError('string index out of range')

Thanks for your help.

**Comment by crazy-max** [comment]
For all matters directly related to fail2ban, please search first on the official repository: https://github.com/fail2ban/fail2ban/issues/2967

**Comment by crazy-max** [comment]
For all matters directly related to fail2ban, please search first on the official repository: https://github.com/fail2ban/fail2ban/issues/2967
